In [91]:
import pandas as pd

In [92]:
data_sentiment=pd.read_csv("/Users/kishankumar/Desktop/get_internship/trader_sentiment_analysis/data/raw/fear_greed_index.csv")
data_historical=pd.read_csv("/Users/kishankumar/Desktop/get_internship/trader_sentiment_analysis/data/raw/historical_data.csv")

In [93]:
data_sentiment.head(10)

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05
5  1517895000      8   Extreme Fear  2018-02-06
6  1517981400     36           Fear  2018-02-07
7  1518067800     30           Fear  2018-02-08
8  1518154200     44           Fear  2018-02-09
9  1518240600     54        Neutral  2018-02-10

In [94]:
print(data_sentiment.isnull().sum())
print("-----------------------------------")
print(data_historical.isnull().sum())

timestamp         0
value             0
classification    0
date              0
dtype: int64
-----------------------------------
Account             0
Coin                0
Execution Price     0
Size Tokens         0
Size USD            0
Side                0
Timestamp IST       0
Start Position      0
Direction           0
Closed PnL          0
Transaction Hash    0
Order ID            0
Crossed             0
Fee                 0
Trade ID            0
Timestamp           0
dtype: int64

In [95]:
print(data_sentiment.dtypes)
print("------------------------------------")
print(data_historical.dtypes)

timestamp          int64
value              int64
classification    object
date              object
dtype: object
------------------------------------
Account              object
Coin                 object
Execution Price     float64
Size Tokens         float64
Size USD            float64
Side                 object
Timestamp IST        object
Start Position      float64
Direction            object
Closed PnL          float64
Transaction Hash     object
Order ID              int64
Crossed                bool
Fee                 float64
Trade ID            float64
Timestamp           float64
dtype: object

In [96]:
print(data_sentiment.duplicated().sum())
print("-------------------------------------")
print(data_historical.duplicated().sum())

0
-------------------------------------
0

In [97]:
print(data_sentiment.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   object
 3   date            2644 non-null   object
dtypes: int64(2), object(2)
memory usage: 82.8+ KB
None

In [98]:
data_sentiment["datetime"] = pd.to_datetime(data_sentiment["timestamp"], unit="s")
data_sentiment["Date"] = data_sentiment["datetime"].dt.date
data_sentiment["Time"] = data_sentiment["datetime"].dt.time

In [99]:
data_sentiment.drop(columns=["timestamp", "datetime","date","datetime"], inplace=True)

In [100]:
data_sentiment["Date"] = pd.to_datetime(data_sentiment["Date"])
data_sentiment["Time"] = pd.to_datetime(data_sentiment["Time"], format="%H:%M:%S")

In [102]:
data_sentiment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   value           2644 non-null   int64
 1   classification  2644 non-null   object
 2   Date            2644 non-null   datetime64[ns]
 3   Time            2644 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(1)
memory usage: 82.8+ KB

In [103]:
data_historical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  object
 1   Coin              211224 non-null  object
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  object
 6   Timestamp IST     211224 non-null  object
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  object
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  object
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), object(6)
memory usage: 24.4+ MB

In [106]:
data_historical.head(10)

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12
5,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9900,1.41,11.27,BUY,02-12-2024 22:50,1298.215466,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.000493,7.330000e+14,1.730000e+12
6,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9934,144.09,1151.77,BUY,02-12-2024 22:50,1299.624972,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,9.060000e+14,1.730000e+12
7,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,8.0000,34.00,272.00,BUY,02-12-2024 22:50,1443.664541,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.011900,3.960000e+14,1.730000e+12
8,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,8.0000,46.00,368.00,BUY,02-12-2024 22:50,1477.652641,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.016100,9.460000e+14,1.730000e+12
9,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,8.0000,12.50,100.00,BUY,02-12-2024 22:50,1523.636541,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.004375,3.470000e+13,1.730000e+12

In [111]:
data_historical["Timestamp IST"] = pd.to_datetime( data_historical["Timestamp IST"], format="%d-%m-%Y %H:%M" )
data_historical["Date"] = data_historical["Timestamp IST"].dt.date
data_historical["Time"] = data_historical["Timestamp IST"].dt.time

In [112]:
data_historical["Date"] = pd.to_datetime(data_historical["Date"])
data_historical["Time"] = pd.to_datetime(data_historical["Time"], format="%H:%M:%S")

In [113]:
data_historical.drop(columns=["Timestamp IST"], inplace=True)

In [114]:
data_historical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  object
 1   Coin              211224 non-null  object
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  object
 6   Start Position    211224 non-null  float64
 7   Direction         211224 non-null  object
 8   Closed PnL        211224 non-null  float64
 9   Transaction Hash  211224 non-null  object
 10  Order ID          211224 non-null  int64
 11  Crossed           211224 non-null  bool
 12  Fee               211224 non-null  float64
 13  Trade ID          211224 non-null  float64
 14  Timestamp         211224 non-null  float64
 15  Date              211224 non-null  datetime64[ns]
 16  Time              211224 non-null  datetime64[ns]
dtypes: bool(1), datetime64[ns](2), float64(8), int64(1), object(5)
memory usage: 26.0+ MB

In [115]:
data_sentiment.to_csv("/Users/kishankumar/Desktop/get_internship/trader_sentiment_analysis/data/processed/fear_greed_index.csv",index=False)
data_historical.to_csv("/Users/kishankumar/Desktop/get_internship/trader_sentiment_analysis/data/processed/historical_data.csv",index=False)